name: Linter
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Go
        uses: actions/setup-go@v5.1.0
        with:
          check-latest: true
          go-version: '1.22'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: latest